site_name: Tự học ngoại ngữ - Khu học mở
site_description: Phương pháp tự học (chắc là) mọi ngoại ngữ thông qua Immersion và Comprehensible Input, completely free.
site_author: duykhanh471
repo_name: Chỉnh sửa trang
repo_url: https://github.com/daihocmo/ngoai-ngu

nav:
  - 'Trang chủ': 'index.md'
  - 'Hướng dẫn tân thủ':
      - 'Tại sao cần tự học ngoại ngữ?': 'phai-tu-hoc.md'
      - 'Trước khi bắt đầu học': 'truoc-khi-bat-dau.md'
  - 'Hướng dẫn học chính':
      - 'Bắt đầu học': 'guide.md'
      - 'Input': 'input.md'
      - 'Nghe': nghe.md
      - 'Đọc': doc.md
      - 'Nói': noi.md
      - 'Đơn ngữ': 'huong-dan-don-ngu.md'
  - 'Câu hỏi thường gặp': 
    - 'FAQ': faq.md
  - 'Xây dựng môi trường học':
      - 'Anki': 'anki.md'
      - 'Yomitan': 'yomitan.md'
      - 'Goldendict': 'goldendict.md'
      - 'Hướng dẫn Mining': 'mining.md'
      - 'Xây dựng môi trường học': setup.md
  - 'Các bài viết khác':
      - 'Tổng quan về Immersion': overview.md
      - 'Sentence Mining': sentence-mining.md
      - 'Language Domain': language-domain.md
  - 'Tài nguyên học':
      - 'Tông hợp': 'resources.md'
 
theme:
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: grey
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  logo: img/logo.svg
  favicon: img/logo.png
  features:
    - navigation.instant
    - navigation.sections
    - search.suggest
    - search.highlighting
    - search.share
  name: material
  
plugins:
  - search
  - open-in-new-tab
  
extra:
  generator: false
  homepage: https://daihocmo.github.io/